overload:
  enabled: true
  package: yandextank.plugins.DataUploader
  token_file: "configs/token.txt"

phantom:
  address: localhost:8080
  ammo_type: uripost
  ammofile: /var/loadtest/ammo.txt
  load_profile:
    load_type: rps # schedule load by defining requests per second
    schedule: const(250, 10m) # starting from 1rps growing linearly to 10rps during 10 minutes
console:
  enabled: true
telegraf:
  enabled: false
